### ISSUE TITLE
Endpoints of Bones are Misplaced

### ISSUE THREAD

**Issue by julmb** [niacdoial/blemd#10]
I tried importing a few models from Twilight Princess (GC) and all the bones' end points are in the wrong place. As you can see in the image below, they all point towards the back. It seems like each end point is  just the start point projected onto some plane parallel to XZ.

![image](https://user-images.githubusercontent.com/11631652/35127920-73c23a5e-fcb4-11e7-999b-77fbe8c492bc.png)

It seems like they still work though, as they are connected in the right way and rotating them seems to have the intended effect on the model.

I'm very new to 3D models so please forgive me if I'm just misunderstanding something here.

**Comment by niacdoial** [comment]
Actually the BMD format doesn't know what a bone endpoint is. The only 
thing it knows is loc-rot-scale transformations.
It has information on "default bone rotation" though, meaning that 
having always parallel bones is wrong.
The current implementation has a dumb, morks-most-of-the-time behavior 
which consists of changing the animation data to match the way blender 
defines those transformation, therefor adapting to the bone orientation.
It is this way because I had to understand how the code was supposed to 
work at the same time as I was actually making it work with Blender.
I plan to fix this at some point, though.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by niacdoial** [comment]
The latest commit "fixed" this, at the same time as the bck animation weirdness.
Now each bone's default orientation is dictated by the bmd file.
However, this orientation has nothing to do with what anyone might be used to (i.e. sticking out of an arm instead of following it from the inside)

**Comment by niacdoial** [comment]
wow, last activity here is older than deltarune.
…I'm gonna close this, since I was just waiting for a "I confirm it works" message
