### ISSUE TITLE
Unable to import anything into Blender 2.79b

### ISSUE THREAD

**Issue by wilgo-uk** [niacdoial/blemd#24]
Over the past few days, I've been trying to import the Mario model from Super Mario Galaxy into Blender (because I would like the animations along with the model), but every time I try to import the model **(Which is a BDL)**, I get this error:
![screenshot from 2018-10-23 18-32-29](https://user-images.githubusercontent.com/17802904/47379734-a47f4000-d6f3-11e8-9cd1-456100705bb0.png)
And this information in the log file:
![screenshot from 2018-10-23 18-33-43](https://user-images.githubusercontent.com/17802904/47379768-bd87f100-d6f3-11e8-9468-f2667c87f629.png)
Now, I thought it would've been causing that because I was using a BDL, so **I tried a BMD** (one converted from the BDL). They both threw up the same error:
![screenshot from 2018-10-23 18-38-00](https://user-images.githubusercontent.com/17802904/47379872-05a71380-d6f4-11e8-8755-968a53dc5a36.png)

Here's the command line output too (although, I don't know how much help this will be):
![screenshot from 2018-10-23 19-02-24](https://user-images.githubusercontent.com/17802904/47380867-5a4b8e00-d6f6-11e8-8396-2e0442b05259.png)

As per the instructions, I have renamed the addon folder from "blemd-master" to "blemd" and I have reinstalled it a few times. I've also used older versions, guessing that it was a bug in the current master release, which got the same errors.

To make sure that it all of the models were working, I used the J3DView located at https://github.com/RenolY2/j3dview and it read all files without issue (Mario in his wait.bck animation): 
![screenshot from 2018-10-23 18-53-25](https://user-images.githubusercontent.com/17802904/47380421-59fec300-d6f5-11e8-9974-981be609d5df.png)
I also used this software to convert the BDL to the BMD

I have tried to use BleMD across Windows 7, Windows 10 and even Ubuntu 18.04 (with Wine and Mono installed, because I noticed an exe file in BleMD) and I still couldn't get it to work.

I'm guessing that I've missed something painfully obvious, but after this many installs, I can't begin to think what the issue is.

**Comment by niacdoial** [comment]
First of all, you did nothing wrong with the way you installed it.
You were just very unlucky because I actually fixed this problem about a day before you opened this issue (see issue #22)
Sorry for the time you lost because of my rookie mistake.

And about other updated having problems, I have to admit that updates ff43027a (14th of october) to df9b9700 (19th of october) have various severe problems (again, my mistake for not testing it more), even though it is a little weird that it seems to be the same problem.

Completely unrelated, but the amount of information you gave me is really impressive. Thanks a lot for that!

**Comment by william-wilgo** [comment]
Hey, thanks! I'll give the new update a go when I get access to my computer later. I'll report back if anything noteworthy happens. (Should be able to update in a few hours)

Also, does it matter much if the model is in BDL or BMD format? Or can it read both without issue?

**Comment by niacdoial** [comment]
As far as I know (a single bdl file and a couple dozen bmd files) it won't crash because the input file is a bdl, but there is still some data from both file formats that cannot be imported,  such as fog and light information for the materials, texture animation, or the 'mdl3' section that shows up in bdl files (all I know is that it affects materials in some way)

**Comment by william-wilgo** [comment]
The addon is now working... almost correctly. There's a new issue with (most likely) the addon. I get these error messages in the tooltip upon importing the model (With each animation on it's own action):
![screenshot from 2018-10-24 18-36-49](https://user-images.githubusercontent.com/17802904/47450426-1f605d80-d7bd-11e8-8534-09f667418a1c.png)

And then the following errors in the console:
![screenshot from 2018-10-24 18-39-30](https://user-images.githubusercontent.com/17802904/47450452-2d15e300-d7bd-11e8-9f12-6b2de4f17956.png)

And once I have resized the model, I get this... for lack of better word, monstrosity:
(Real footage from game in lower-left, they may not be synced up perfectly)
![smgblender](https://user-images.githubusercontent.com/17802904/47450552-749c6f00-d7bd-11e8-9f67-55ef072328a7.gif)

The program that I used to verify the model plays back the animation fine, so I guess that this another bug in BleMD. I haven't tried to import everything on the same action because that begun to take forever to do and almost crashed the program.

**Comment by niacdoial** [comment]
Okay. This is actually three problems at once.
The first is the bunch of "float: division by zero" messages, that I didn't have the time to find the source of.
The second one conserns the "zero is nonzero" messages: it means that the animation works in a way that is somewhat unknown to BleMD. It tries anyway, but this is probably the cause of the weird motion.
It might be the cause of the previous problem, but it would mean that warning and errors should be directly next to each other.

Final problem, about the white face and the blue gloves: the materials don't seem to be applied correctly, in a way that looks like the effects of the "validate mesh [!]" option.
I didn't include it in the docs yet, but basically it is only to be used of blender crashes otherwise (hence the "[!]" at the end of the option name)

**Comment by niacdoial** [comment]
Sorry for the delay, but I think I have fixed every bug (except maybe the "Error: +inf" one) mentioned in your last big post. (I can't say for sure because I don't have these animations, only similar ones)
