### ISSUE TITLE
Imports have Red Textures

### ISSUE THREAD

**Issue by PeculiarPancakes** [niacdoial/blemd#31]
Just found this script and I can finally view and export the TP BMD files I have, but the only snag is that none of the textures work. Every time I import a BMD file, it gives me an error and colours all of the materials red with no texture image. Is this a well known issue? Does this script not have the ability to include the img textures yet?
<img width="1680" alt="Screen Shot 2019-07-03 at 7 33 06 PM" src="https://user-images.githubusercontent.com/52513330/60630916-8dd4d100-9dca-11e9-92fe-1a37c343a1a4.png">

**Comment by niacdoial** [comment]
Hello,
so er..
The thing is, because exporting the textures from the bmd file is such a heavy task, it is actually handled by a small c++ program shipped with the addon.
sadly, I didn't compile it for mac (yet? I don't own a mac so...), which is why the textures don't show up.
However, the source for this small program is in the "image importing subprocess" folder, if you can compile it. You will also have to modify part of the "common.py" file for it to find the executable.

**Comment by PeculiarPancakes** [comment]
Alright, that's understandable, i've run into this sort of thing a lot. Thank you anyways for the response

**Comment by niacdoial** [comment]
One thing though.
Since I compiled it for linux (or at least ubuntu 18.04, 64bit), you could set up a virtual machine to get the textures.
(I know, windows+linux support but not mac support is an uncommon combination)
